# grader/checks/m1/instructions_contract.py
from __future__ import annotations
from pathlib import Path
from typing import List, Dict
from grader.core.models import Severity
from grader.utils_fs import read_text, normalize_for_hash, sha256
from grader.checks.m1.common import ok, fail, msg


ANCHORS = [
    "# Milestone 1: Foundations – Problem Understanding & High-Level Design",
    "## สิ่งที่ต้องส่ง (Deliverables)",
    "## สิ่งที่ **ไม่ควรทำ** ใน Milestone นี้",
    "[Student Fill In]",
    "รายละเอียดคะแนนดูได้จาก `PROJECT_SPEC.md`",
]


def check_instructions_exists(repo: Path):
    check_id = "M1.CONTRACT.01"
    title = "INSTRUCTIONS.md exists"
    possible = 2
    path = repo / "milestone1" / "INSTRUCTIONS.md"
    if path.exists():
        return ok(check_id, title, possible)
    return fail(
        check_id, title, 0, possible,
        [msg(
            Severity.BLOCKER,
            "Missing milestone1/INSTRUCTIONS.md",
            "INSTRUCTIONS.md เป็น contract ของ Milestone 1 และระบุว่า “ห้ามแก้ไข”",
            ["Restore file from the assignment template repository.", "Commit and push again."],
            evidence=str(path),
        )],
    )


def check_instructions_anchors(repo: Path):
    check_id = "M1.CONTRACT.02"
    title = "INSTRUCTIONS.md anchors intact"
    possible = 6
    path = repo / "milestone1" / "INSTRUCTIONS.md"
    if not path.exists():
        return fail(
            check_id, title, 0, possible,
            [msg(
                Severity.BLOCKER,
                "Cannot check anchors because INSTRUCTIONS.md is missing",
                "Contract file must exist before we can validate its contents.",
                ["Restore milestone1/INSTRUCTIONS.md from template."],
                evidence=str(path),
            )],
        )

    text = read_text(path)
    missing = [a for a in ANCHORS if a not in text]
    if not missing:
        return ok(check_id, title, possible)

    return fail(
        check_id, title, 0, possible,
        [msg(
            Severity.BLOCKER,
            f"INSTRUCTIONS.md missing required contract anchors: {', '.join(missing)}",
            "INSTRUCTIONS.md เป็น contract ของ milestone; หาก anchor หายแปลว่าไฟล์ถูกแก้ไข/เสียรูป",
            ["Revert milestone1/INSTRUCTIONS.md to the exact template version.",
             "Avoid editing this file (it is marked 'ห้ามแก้ไข')."],
            evidence=str(path),
        )],
        debug={"missing_anchors": missing},
    )


def check_instructions_normalized_hash(repo: Path, canonical_hash: str | None):
    """
    Optional strict check: pass canonical_hash=None to disable.
    """
    check_id = "M1.CONTRACT.03"
    title = "INSTRUCTIONS.md unchanged (normalized hash)"
    possible = 4
    if canonical_hash is None:
        # disabled => give full score (or 0/0 if you prefer)
        return ok(check_id, title, possible, debug={"disabled": True})

    path = repo / "milestone1" / "INSTRUCTIONS.md"
    if not path.exists():
        return fail(
            check_id, title, 0, possible,
            [msg(Severity.MAJOR, "INSTRUCTIONS.md missing", "Cannot verify contract integrity.", ["Restore from template."], str(path))],
        )

    norm = normalize_for_hash(read_text(path))
    h = sha256(norm)
    if h == canonical_hash:
        return ok(check_id, title, possible, debug={"hash": h})

    return fail(
        check_id, title, 0, possible,
        [msg(
            Severity.MAJOR,
            "INSTRUCTIONS.md content differs from the template (normalized)",
            "This file is a contract; changing it can confuse graders and break autograding assumptions.",
            ["Revert milestone1/INSTRUCTIONS.md from the template repository.",
             "Do not edit this file."],
            evidence=f"{path} (hash={h})",
        )],
        debug={"expected_hash": canonical_hash, "actual_hash": h},
    )
