from ._util import repo, read_text

ANCHORS = [
    "# Milestone 1: Foundations – Problem Understanding & High-Level Design",
    "## สิ่งที่ต้องส่ง (Deliverables)",
    "## สิ่งที่ **ไม่ควรทำ** ใน Milestone นี้",
    "[Student Fill In]",
    "รายละเอียดคะแนนดูได้จาก `PROJECT_SPEC.md`",
]

def run(ctx):
    path = repo(ctx) / "milestone1" / "INSTRUCTIONS.md"
    if not path.exists():
        return 0, 6, "[BLOCKER] INSTRUCTIONS.md missing; cannot validate anchors."

    text = read_text(path)
    missing = [a for a in ANCHORS if a not in text]
    if not missing:
        return 6, 6, "OK: INSTRUCTIONS.md contract anchors intact"

    return 0, 6, (
        "[BLOCKER] INSTRUCTIONS.md appears modified (missing contract anchors)\n"
        f"Missing: {', '.join(missing)}\n"
        "Why: INSTRUCTIONS.md is a contract; changing it breaks grading assumptions.\n"
        "Fix:\n"
        "- Revert milestone1/INSTRUCTIONS.md to the template version.\n"
        "- Do not edit this file."
    )
